name: CD Pipeline

on:
  push:
    branches:
      - devops

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          IMAGE_TAG="latest"
          docker buildx build --tag myapp:${IMAGE_TAG} --file Dockerfile .

      - name: Save and Compress Docker Image
        run: |
          IMAGE_TAG="latest"
          docker save myapp:${IMAGE_TAG} | gzip > myapp-${IMAGE_TAG}.tar.gz

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: myapp-${IMAGE_TAG}.tar.gz

  deploy_to_server:
    needs: build_and_deploy
    runs-on: ubuntu-latest

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: .

      - name: Transfer Docker Image to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: myapp-${IMAGE_TAG}.tar.gz
          target: /tmp/php

      - name: Load and Deploy Docker Image on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            IMAGE_TAG="latest"
            cd /tmp/php
            gunzip myapp-${IMAGE_TAG}.tar.gz
            docker load < myapp-${IMAGE_TAG}.tar
            rm -f myapp-${IMAGE_TAG}.tar
