name: PR Deploy

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy-pr:
    environment: 
      name: preview
      url: ${{ steps.deploy.outputs.preview-url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .
          docker save -o my-app.tar my-app:latest

      - name: Upload Docker image to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          scp -o StrictHostKeyChecking=no my-app.tar $SSH_USER@$SSH_HOST:/var/www/langlearnai-be/deployment

      - name: Deploy Docker image on server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            docker load -i /var/www/langlearnai-be/deployment/my-app.tar
            cd /var/www/langlearnai-be/deployment
            docker-compose -f docker-compose.staging.yml down
            docker-compose -f docker-compose.staging.yml up -d
          EOF

      - name: Print Preview URL
        run: |
          echo "Preview URL: http://$SSH_HOST"
