name: PR Deploy

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy-pr:
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.preview-url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          PR_TAG="pr-${{ github.event.pull_request.number }}"
          docker build -t my-app:${PR_TAG} .
          docker save -o my-app-${PR_TAG}.tar my-app:${PR_TAG}

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Upload Docker image to server
        run: |
          PR_TAG="pr-${{ github.event.pull_request.number }}"
          scp -o StrictHostKeyChecking=no my-app-${PR_TAG}.tar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv

      - id: deploy
        name: Pull Request Deploy
        uses: hngprojects/pr-deploy@v1.1.9
        with:
          server_host: ${{ secrets.SSH_HOST }}
          server_username: ${{ secrets.SSH_USER }}
          comment: true
          context: '.'
          dockerfile: 'Dockerfile'
          host_volume_path: '/srv'
          container_volume_path: '/srv'

      - name: Print Preview URL
        run: |
          echo "Preview URL: ${{ steps.deploy.outputs.preview-url }}"

      - name: Deploy Docker image on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            docker load -i /srv/my-app-${{ github.event.pull_request.number }}.tar
            cd /var/www/langlearnai-be/pr
            git pull origin dev
            docker-compose -f docker-compose.staging.yml down
            docker-compose -f docker-compose.staging.yml up -d
          EOF
