name: PR Deploy

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy-pr:
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.preview-url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .
          docker save -o my-app.tar my-app:latest

      - id: deploy
        name: Pull Request Deploy
        uses: hngprojects/pr-deploy@v1.1.9
        with:
          server_host: ${{ secrets.SSH_HOST }}
          server_username: ${{ secrets.SSH_USER }}
          server_password: ${{ secrets.SSH_PASSWORD }}
          comment: true
          context: '.'
          dockerfile: 'Dockerfile'
          host_volume_path: '/var/www/langlearnai-be/deployment'
          container_volume_path: '/var/www/langlearnai-be/deployment'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Preview URL
        run: |
          echo "Preview URL: ${{ steps.deploy.outputs.preview-url }}"

      - name: Deploy Docker image on server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            scp -o StrictHostKeyChecking=no my-app.tar $SSH_USER@$SSH_HOST:/var/www/langlearnai-be/deployment
            docker load -i /var/www/langlearnai-be/deployment/my-app.tar
            cd /var/www/langlearnai-be/deployment
            docker-compose -f docker-compose.staging.yml down
            docker-compose -f docker-compose.staging.yml up -d
          EOF
