name: Release
on:
  push:
    branches:
      - main
  
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init
        run: |
          rm package.json 
          rm package-lock.json
          
      - name: Exit Folder
        run: |
          cd ..
          ls
          pwd
      
      - name: Release to GitHub
        uses: cycjimmy/semantic-release-action@v4
        with:
        # You can specify specifying version range for the extra plugins if you prefer.
            extra_plugins: |
                @semantic-release/changelog@6.0.0
                @semantic-release/git
            branches: |
                ['main']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
